---
- hosts: hockeypuck
  sudo: yes
  tasks:
  - name: Stop Hockeypuck
    service: name=hockeypuck state=stopped
  - name: Development rebuild
    local_action: shell go build -o files/hockeypuck github.com/squeed/hockeypuck/cmd/hockeypuck
    sudo: no
  - name: Replace Hockeypuck binary
    copy: src=files/hockeypuck dest=/usr/bin/hockeypuck mode=0755 force=yes
  - name: Start Hockeypuck
    service: name=hockeypuck state=started
